version: '3.4'

services:
  auction-react-app:
    image: tg-auction-react-app
    build:
      context: ./auction-react-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./auction-react-app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
  tg-auction-bot:
    image: tg-auction-bot
    build:
      context: ./telegram-api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      DB_NAME: auction_db
      DB_HOST: db
    ports:
      - 3001:3001
    volumes:
      - ./telegram-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
    - app-network
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: auction_db
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
networks:
  app-network: 
    driver: bridge